markup-ementor-footer
ivan1945kozhevnikov/interface-components pull request #3
Opened 2024-07-11 08:43 UTC by ivan1945kozhevnikov

2024-07-14 08:15 UTC, ivan1945kozhevnikov commented on footer/ementor-footer/index.html
> +            <a href="#" class="site-footer__learning-link">Курсы</a>
service-navigation__link

2024-07-14 08:15 UTC, ivan1945kozhevnikov commented on footer/ementor-footer/index.html
> +        <div class="site-footer__email">
p class="footer__email-title" Возникли вопросы?

2024-07-14 08:15 UTC, ivan1945kozhevnikov commented on footer/ementor-footer/index.html
> +          <p class="site-footer__email-information">
подумать над названием

2024-07-14 08:15 UTC, ivan1945kozhevnikov commented on footer/ementor-footer/index.html
> +            <a href="#" class="site-footer__email-link">
заменить href="#"

2024-07-14 08:15 UTC, ivan1945kozhevnikov commented on footer/ementor-footer/index.html
> +        <p class="container-footer__description-text">
footer__copyright

2024-07-14 08:15 UTC, ivan1945kozhevnikov commented on footer/ementor-footer/index.html
> +        <a href="#" class="container-footer__description-link">
footer__link

2024-07-15 08:26 UTC, dmitryermolenko requested changes

2024-07-15 08:26 UTC, dmitryermolenko commented on footer/ementor-footer/index.html
> +            <li class="social-item">
это не блок, а элемент

2024-07-15 08:26 UTC, dmitryermolenko commented on footer/ementor-footer/index.html
> +              <a href="#" class="social-link">
это не блок, а элемент

2024-07-15 08:26 UTC, dmitryermolenko commented on footer/ementor-footer/index.html
> +                  class="social-icon"
это не блок, а элемент

2024-07-15 08:26 UTC, dmitryermolenko commented on footer/ementor-footer/index.html
> +            <li class="social-item">
это не блок, а элемент

2024-07-15 08:26 UTC, dmitryermolenko commented on footer/ementor-footer/index.html
> +              <a href="#" class="social-link">
это не блок, а элемент

2024-07-15 08:26 UTC, dmitryermolenko commented on footer/ementor-footer/index.html
> +                  class="social-icon"
это не блок, а элемент

2024-07-15 08:26 UTC, dmitryermolenko commented on footer/index.html
> +    <a href="ementor-footer/index.html">Навигация на сайте E-Mentor</a>
Это же не навигация

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +    <title>Document</title>
Заголовок адекватный нужен

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +            width="128"
убрать размеры и заливку

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +              fill="#353A5A"
убрать заливку

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +              fill="#353A5A"
убрать заливку

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +              fill="#353A5A"
убрать заливку

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +              fill="#353A5A"
убрать заливку

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +              fill="#353A5A"
убрать заливку

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +              fill="#353A5A"
убрать заливку

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +              fill="#353A5A"
убрать заливку

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +              fill="#FA9F42"
убрать заливку

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +              fill="#FA9F42"
убрать заливку

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +              fill="#FA9F42"
убрать заливку

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +          <li class="site-navigation__item">
site-navigation__item  ты не используешь в стилях

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +          <li class="site-navigation__item">
site-navigation__item  ты не используешь в стилях

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +          <li class="site-navigation__item">
site-navigation__item  ты не используешь в стилях

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +          <li class="site-navigation__item">
site-navigation__item  ты не используешь в стилях

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +          <li class="site-navigation__item">
site-navigation__item  ты не используешь в стилях

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +          <li class="site-navigation__item">
site-navigation__item  ты не используешь в стилях

2024-07-15 08:26 UTC, dmitryermolenko commented on navigation/ementor-navigation/index.html
> +          <li class="site-navigation__item">
site-navigation__item  ты не используешь в стилях

2024-07-17 09:40 UTC, merged